# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Markov Wanderer
tagline:             'A blog on economics, science, coding and data. Views are my own.'
description:         'More...'
url:                 http://aeturrell.github.io/home
baseurl:             http://aeturrell.github.io/home # change to '' for local
paginate:            5
plugins: [jekyll-paginate, jekyll-feed]
paginate_path: blog/page:num

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# About/contact
author:
  name:              Arthur Turrell
  url:
  email:

# Custom vars
version:             1.0.0
