# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Dr. Arthur Turrell
tagline:             'Welcome to my personal website'
description:         'Welcome to my personal website'
url:                 http://aeturrell.github.io/home/
baseurl:             http://aeturrell.github.io/home/
paginate:            5
plugins: [jekyll-paginate]

# About/contact
author:
  name:              Arthur Turrell
  url:
  email:

# Custom vars
version:             1.0.0
