# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Markov Wanderer
tagline:             'Blog'
description:         'More...'
url:                 http://aeturrell.github.io/home/blog/
baseurl:             http://aeturrell.github.io/home/blog/ # change to '' for local
paginate:            5
plugins: [jekyll-paginate]

# About/contact
author:
  name:              Arthur Turrell
  url:
  email:

# Custom vars
version:             1.0.0
