---
title: What I use
date: 2024-12-10
date-format: "DD MMM YYYY"
description-meta: The tools for the job(s)
title-block-banner: "#771C6D"
published-title: Last updated
toc: true
toc-location: left
toc-title: "Contents"
---

This page contains a list of the tools I'm using for research or at home. Most of what I use regularly is free and open source software (FOSS), not because I'm ideological (you'll see some paid apps too), but because FOSS often produces tools that are effective and convenient. Because I work in the public sector, I often have to use very different software and hardware at work—mostly tech that I wouldn't recommend to anyone. This is why the list is focused on research and home purposes. One of my missions is to unlock the productivity benefits of frontier tech (including FOSS) for the public sector!

## Reading and writing

- *Document writing*. I never got into the Microsoft Office suite of tools that includes Word. I've had to use Word for work a lot and I struggle to find much good to say about it. I do the majority of my writing for others (including this website and blog) in [Markdown](https://daringfireball.net/projects/Markdown/), or [Quarto](https://quarto.org), which is basically also Markdown! Some of the benefits of writing in Markdown are that it's intuitive, readable, flexible, future proof, interoperable with many other programmes, and it allows you to focus on content. If I need to get a Word document out of the end, I use either [Pandoc](http://pandoc.org/) or [Quarto](https://quarto.org). With Pandoc, it's a line like
    ```bash
    pandoc briefing.md -V geometry:margin=0.2in --standalone \
    --bibliography references.bib --citeproc --csl=harvard.csl -o briefing.docx
    ```

    applied to a file called "briefing.md", a bibtex file of references ("references.bib"), and a citation style (here "harvard.csl"). It's fairly similar to using [Quarto to generate a Word document](https://quarto.org/docs/output-formats/ms-word.html). For more elaborate documents, like a book manuscript, I've created a couple of helper tools like [this quarto template](https://github.com/aeturrell/cookie-cutter-quarto-book-manuscript).
- *Note taking*. I store general notes in Microsoft [OneNote](https://www.onenote.com/) but for single projects that are bigger and more complex (perhaps with many interlocking themes) I now use the truly excellent [Obsidian](https://obsidian.md/). Obsidian is a clean text Markdown-based note-taking system that separates the data (Markdown files) from the viewer/editor in a way that means you always stay in control of your own data. If you want a seamless experience across phone, tablet, and computer, you'll need to pay for their storage.
- *Text editor*. I use Microsoft's [Visual Studio Code](https://code.visualstudio.com/) (with the Markdown all in one and Markdown preview enhanced extensions) for all text, including writing Markdown. [Obsidian](https://obsidian.md/) is a fine Markdown editor too. I've yet to try alternatives such as [Ulysses](http://ulyssesapp.com/), [Marked](http://marked2app.com/), and [Typora](https://typora.io/).
- *Writing papers*. For papers, I've now switched to using Markdown/[Quarto](https://quarto.org). You can find a [cookie-cutter research template with paper and slides here](https://github.com/aeturrell/cookiecutter-research-project). You can insert figures, tables, *and* numbers into text, including in-line, so that the paper and slides can be completely updated if the results change. That makes it perfect for reproducible analytical pipelines. You can also export to LaTeX. I still use LaTeX from time to time. Although Visual Studio Code has a LaTeX editor that's very good, I use [TeXshop](https://pages.uoregon.edu/koch/texshop/) for LaTeX editing.
- *Reading papers*. I store papers in [Zotero](https://www.zotero.org/), which is an open source endeavour. You can support them by paying for their storage. They have an excellent iPad app too. Even better, [you can sync your papers and notes with Obsidian](../blog/posts/til-zotero-and-obsidian/index.md).

## Coding and development

- *Version control*. I use [git](https://git-scm.com/) and [GitHub](https://github.com/).
- *Development environment*. I use [Visual Studio Code](https://code.visualstudio.com/) for almost all code, including Python and R. (I wrote a post about how to set it up for R [here](../blog/posts/setting-up-r-in-vscode/index.md).) I also use Docker for development, including the excellent Visual Studio Code docker extensions.
- *Cloud compute*. When I need cloud capabilities, I mostly go for [Google Cloud](https://cloud.google.com/), connecting via Visual Studio Code remote (instructions in [this post](../blog/posts/visual-studio-code-in-the-cloud/index.md).)
- *Package manager*. To install things sensibly on a Mac, I use [Homebrew](https://brew.sh/).
- *Terminal*:
    - [ghostty](https://ghostty.org/) for my terminal
    - [ohmyzsh](https://ohmyz.sh/) for zsh configuration
    - [ohmyposh](https://ohmyposh.dev/) as a prompt engine
    - [lsd](https://github.com/lsd-rs/lsd) as a replacement for `ls`
    - [wget](https://www.gnu.org/software/wget/) for downloads
    - [ripgrep](https://github.com/BurntSushi/ripgrep) for text-in-file search
    - [llm](https://github.com/simonw/llm) to run local and remote large language models
    - [duckdb -ui](https://duckdb.org/2025/03/12/duckdb-ui) for exploring SQL databases
    - [ffmpeg](https://ffmpeg.org/) for converting audio and video
    - [imagemagick](https://imagemagick.org/) for working with image files
    - [f2](https://github.com/ayoisaiah/f2) for bulk renaming files
    - [Inkscape](https://inkscape.org/) on the command line, mainly for converting things to svg 
- *Programming language*. My default is Python, for a whole host of reasons, with, of course, some SQL. I am a huge convert to [uv](https://docs.astral.sh/uv/) and now use it to install Python, build packages, and manage repo packages. With more complex projects that require dependencies that are not pure Python (eg the PyMC package), I use the [Miniconda](https://docs.anaconda.com/miniconda/) distribution of Python with its fast extension [Mamba](https://github.com/mamba-org/mamba).
- *Building Python packages*. There's [a template for that](https://github.com/aeturrell/cookiecutter-python-package)! 
- *Hardware*. I use a 2021 MacBook Pro with the M1 Max chip, which is inexplicably powerful: so much so that, in 2001, it would have been the world's fastest supercomputer.

## Communication

- *Email and Calendar*. I use [Spark](https://sparkmailapp.com/) (Mac) for emails, but don't have a fancy calendar app and tend to use Apple's default offering, Calendar. [Fantastical](https://flexibits.com/fantastical) looks interesting but because my schedule is mostly bound to a locked-down version of Outlook, a fancy calendar app isn't all that helpful.
- *Communicating about analysis*. Recently, I've ended up communicating about papers via WhatsApp, but this is unsatisfactory on multiple levels and if something more serious and sensible were needed I'd probably opt for [Slack](https://slack.com/intl/en-gb) or [discord](https://discord.com/). Email tends to be the most common still though.
- *Slide shows*. My preference is to use written notes over slide decks whenever possible (you can read a bit more about why [here](../blog/posts/managing-public-sector-knowledge/managing-public-sector-knowledge.qmd#notes-should-be-the-default-with-microsoft-powerpoint-presentations-only-by-exception)), following the [Amazon model](https://www.managementtoday.co.uk/why-amazon-banned-powerpoint/leadership-lessons/article/1689543). But you need a slide show now and again! If it's leaning toward a general audience and it covers a wide range of topics, I'll typically use [Keynote](https://www.apple.com/uk/keynote/). I know it isn't cross-platform, but you can create something that looks good in it quickly and easily—and you can export every stage of builds to PDF too. For giving talks on research papers, I used to reach for [beamer](https://ctan.org/pkg/beamer) and LaTeX but I now use [Quarto for slides](https://quarto.org/docs/presentations/) because everything can be programmatically re-generated if results change, it plays nicely with code chunks and code execution, and the HTML slides you can create are pretty nice. Again, check out the research project template [here](https://github.com/aeturrell/cookiecutter-research-project)
- *Website*. I use [Quarto](https://quarto.org/) and [Github pages](https://pages.github.com/), a powerful combination. For the website code, I'm indebted to [Andrew Heiss](https://www.andrewheiss.com/) for making the code for his website available.

## Misc

- For graphics, I normally go for [matplotlib](https://matplotlib.org/), which is so much more powerful than most people realise. All of the graphics in my book [The Star Builders](../thestarbuilders/thestarbuilders.qmd) were created using matplotlib. If I need a manual programme for graphics, I normally use [Inkscape](https://inkscape.org/), which is much better on Mac than it once was.
- I keep track of tasks with the excellent [Things](https://culturedcode.com/things/) (Mac).
- For timing how long I spend on different tasks or projects, I use a combination of [Timery](https://timeryapp.com/) on top of [Toggl](https://toggl.com/).
- For fonts, [Nerd Fonts](https://www.nerdfonts.com/) is good, as are the [GitHub ones](https://github.com/githubnext/monaspace). For a much wider selection, there's always [Google Fonts](https://fonts.google.com/).
